bind_addr: 0.0.0.0
bind_port: 8888

log_dir: ./log

mysql_config:
  user: root
  password: nike0810
  host: 127.0.0.1
  port: 3306
  db_name: culture
  params: charset=utf8mb4&parseTime=True
  max_idle_conns: 10
  max_open_conns: 100
