bind_addr: 0.0.0.0
bind_port: 8900
base_url: http://121.5.100.186:8900
https_base_url: https://121.5.100.186:8900

cookie_domain: 121.5.100.186

log_dir: ./log
media_save_basedir: /home/greetlist/workspace/CultureWeb/web_admin/media/
media_base_url: media/

article_save_basedir: /home/greetlist/workspace/CultureWeb/web_admin/article/
article_base_url: article/

redis_config:
  pool_size: 10
  redis_server: 127.0.0.1
  redis_port: 6379

tls_config:
  server_crt: /home/greetlist/tls_ca/server.crt
  server_key: /home/greetlist/tls_ca/server.key

mysql_config:
  user: root
  password: nike0810
  host: 127.0.0.1
  port: 3306
  db_name: culture
  params: charset=utf8mb4&parseTime=True
  max_idle_conns: 10
  max_open_conns: 100

token_config:
  token_name: "culture_web"
  token_expire_time: 28800

web_basic_info:
  web_name: "荔波文化馆"
  address: "建设路2号（现小十字老百货门市处）"
  phone_number: "2022‑4233465"
  contact_name: "张飞"
