name: web_admin
on:
  push:
    branches:
      - master
      - release
    paths-ignore:
      - 'web_admin/frontend/**'
      - 'web_front/**'
  pull_request:
    branches:
      - master
      - release
    paths-ignore:
      - 'web_admin/frontend/**'
      - 'web_front/**'

jobs:
  Build-Test-Binary:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Down load go packages
      run: export GOPROXY=https://goproxy.io && go install github.com/swaggo/swag/cmd/swag@latest
    - name: Build with make
      run: |
        export GITHUB_PATH=$GITHUB_PATH:/home/greetlist/workspace/bin
        cd web_admin/server/ && make -j4
