name: web_admin
on:
  push:
    paths-ignore:
      - 'web_admin/frontend/**'
      - 'web_front/**'
  pull_request:
      paths-ignore:
      - 'web_admin/frontend/**'
      - 'web_front/**'

jobs:
  Build-Test-Binary:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Down load go packages
      run: export GOPROXY=https://goproxy.io && go install github.com/swaggo/swag/cmd/swag@latest
    - name: Print some var
      run: |
        echo $GITHUB_PATH
        export GITHUB_PATH=$GITHUB_PATH:/home/greetlist/workspace/bin
        echo $GITHUB_PATH
        swag -h
    - name: Build with make
      run: |
        export GITHUB_PATH=$GITHUB_PATH:/home/greetlist/workspace/bin
        cd web_admin/server/ && make -j4
